name: theWarn
version: 1.3.1
api: 3.0.0
main: supercrafter333\theWarn\theWarn
author: supercrafter333

commands:
  thewarn:
    description: "Warn a player!"
    aliases: ["twarn", "warn"]
  thewarnunban:
    description: "Unban a banned player by thWarn!"
    aliases: ["twunban", "twu"]

permissions:
  thewarn.cmd:
    default: op
    children:
      thewarn.warn.command:
        description: Warn a player
        default: op
      thewarn.thewarnunban.cmd:
        description: Unban a banned player by theWarn
        default: op
